name: is-interactive-element
on:
    release:
        types: published

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/cache@v1
              with:
                  path: ~/.npm
                  key: npm-${{ hashFiles('**/package-lock.json') }}
            - uses: actions/setup-node@v1
              with:
                  node-version: 12
            - run: npm ci
            - run: |
                  npm config set "//registry.npmjs.org/:_authToken" "${NPM_TOKEN}"
                  npm run publish
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
